import { Card, CardHeader, CardBody } from '../ui/Card.jsx';
import { formatCurrency } from '../../utils/format.js';

/** The simulated day's price range for a stock. */
export const MarketDataCard = ({ quote }) => {
  const items = [
    { label: 'Open', value: formatCurrency(quote.previousClose) },
    { label: 'Previous close', value: formatCurrency(quote.previousClose) },
    { label: "Day's high", value: formatCurrency(quote.dayHigh) },
    { label: "Day's low", value: formatCurrency(quote.dayLow) },
  ];

  return (
    <Card className="h-100">
      <CardHeader title="Market data" subtitle="Simulated quote" icon="fa-chart-line" />
      <CardBody>
        <div className="row g-3">
          {items.map((item) => (
            <div className="col-6 col-md-3" key={item.label}>
              <div className="p-3 rounded h-100" style={{ background: 'var(--tn-canvas)' }}>
                <div className="tn-stat-label">{item.label}</div>
                <div className="tn-num fw-semibold" style={{ color: 'var(--tn-ink)' }}>
                  {item.value}
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="alert alert-secondary small mt-3 mb-0 d-flex align-items-start gap-2" role="note">
          <i className="fa-solid fa-circle-info mt-1" aria-hidden="true" />
          <span>
            These prices are generated by a simulated feed for demonstration. They are not real
            market data and must not inform any investment decision.
          </span>
        </div>
      </CardBody>
    </Card>
  );
};
